// 📂 src/app/features/admin/loyalty-intelligence/actions/getLoyaltyExecutiveSummary.ts

"use server";

import connectMongoose from "@/app/shared/lib/checkout/mongoose";
import Order from "@/models/Order";
import { redis } from "@/app/shared/lib/telemetry/rate-limiter";
import { verifyAdminAccess } from "@/app/features/admin/analytics-telemetry/action/verifyAdminAccess";

// ✅ SINGLE SOURCE OF TRUTH
import { REVENUE_STATUSES } from "@/app/shared/constants/analytics";

// ✅ SAFE SERIALIZE UTILITIES
import { safeStringify, safeParse } from "@/app/shared/lib/utils/safeSerialize";

// ================================================================
// ✅ TYPES (100% Preserved)
// ================================================================
export interface CustomerCohortMetrics {
  totalUsers: number;
  totalOrders: number;
  totalRevenue: number;
  averageOrderValue: number; // Revenue / Orders
  lifetimeValue: number; // Revenue / Users
  repeatPurchaseRate: number; // Users with > 1 order / Total Users
  topProducts?: string[];
}

export interface LoyaltyExecutiveSummaryResponse {
  referred: CustomerCohortMetrics;
  organic: CustomerCohortMetrics;
  comparison: {
    revenuePremium: number; // (Referred LTV - Organic LTV) / Organic LTV * 100
    repeatPremium: number; // (Referred Repeat Rate - Organic Repeat Rate)
    aovPremium: number; // (Referred AOV - Organic AOV) / Organic AOV * 100
    revenueImpact: number; // Total extra revenue generated by referral program
  };
  generatedAt: string;
}

// ================================================================
// 🛡️ CACHE STAMPEDE PROTECTION (Lua Script)
// ================================================================
const LUA_RELEASE_LOCK = `
  if redis.call("get", KEYS[1]) == ARGV[1] then
    return redis.call("del", KEYS[1])
  else
    return 0
  end
`;

const releaseLock = async (lockKey: string, requestId: string): Promise<void> => {
  try {
    const result = await redis.eval(LUA_RELEASE_LOCK, [lockKey], [requestId]);
    if (result === 1) console.log(`🔓 Loyalty Exec Lock released (${requestId}).`);
  } catch (error) {
    console.error("Loyalty Exec Lock release error:", error);
  }
};

// ================================================================
// 🔨 HELPER: Calculate cohort metrics from grouped user data
// ================================================================
function calculateCohortMetrics(
  userOrders: { userId: string; orderCount: number; totalSpend: number }[]
): CustomerCohortMetrics {
  const totalUsers = userOrders.length;
  const totalOrders = userOrders.reduce((sum, u) => sum + u.orderCount, 0);
  const totalRevenue = userOrders.reduce((sum, u) => sum + u.totalSpend, 0);
  const repeatUsers = userOrders.filter((u) => u.orderCount > 1).length;

  return {
    totalUsers,
    totalOrders,
    totalRevenue,
    averageOrderValue: totalOrders > 0 ? totalRevenue / totalOrders : 0,
    lifetimeValue: totalUsers > 0 ? totalRevenue / totalUsers : 0,
    repeatPurchaseRate: totalUsers > 0 ? (repeatUsers / totalUsers) * 100 : 0,
  };
}

// ================================================================
// 🚀 MAIN FUNCTION — Enterprise Ready
// ================================================================
export async function getLoyaltyExecutiveSummary(): Promise<{
  success: boolean;
  data?: LoyaltyExecutiveSummaryResponse;
  error?: string;
}> {
  const cacheKey = "analytics_loyalty_executive_summary_v6";

  try {
    // 1. RBAC
    await verifyAdminAccess();

    // 2. Cache Check (using safeParse)
    const cachedData = await redis.get(cacheKey);
    const parsed = safeParse<LoyaltyExecutiveSummaryResponse>(cachedData as string | null);
    if (parsed) {
      console.log("⚡ Redis Cache Hit: Loyalty Executive Summary");
      return { success: true, data: parsed };
    }

    // 3. Lock for Cache Stampede
    const LOCK_TTL = 30;
    const lockKey = `lock:${cacheKey}`;
    const requestId = `lock_${Date.now()}_${Math.random().toString(36).substring(2, 8)}`;
    const lockAcquired = await redis.set(lockKey, requestId, { nx: true, ex: LOCK_TTL });

    if (!lockAcquired) {
      console.log("⏳ Cache Stampede Detected. Waiting 500ms...");
      await new Promise((resolve) => setTimeout(resolve, 500));
      const retryCache = await redis.get(cacheKey);
      const retryParsed = safeParse<LoyaltyExecutiveSummaryResponse>(retryCache as string | null);
      if (retryParsed) {
        return { success: true, data: retryParsed };
      }
    }

    try {
      console.log(`🔒 Loyalty Exec Lock acquired (${requestId}). Generating executive summary...`);

      await connectMongoose();

      // ================================================================
      // 🔥 1. AGGREGATION: Group orders by user, attach referral status
      // ================================================================
      const userOrderAggregation = await Order.aggregate([
        // ✅ Match valid sales orders with non-empty user IDs
        {
          $match: {
            status: { $in: REVENUE_STATUSES },
            userId: { $exists: true, $ne: "" },
          },
        },
        // ✅ FIX 1: Safe conversion to ObjectId using $convert (onError: null prevents BSON crashes on custom string IDs!)
        {
          $addFields: {
            userObjId: {
              $convert: {
                input: "$userId",
                to: "objectId",
                onError: null,
                onNull: null,
              },
            },
          },
        },
        // ✅ Join with User collection
        {
          $lookup: {
            from: "users",
            localField: "userObjId",
            foreignField: "_id",
            as: "userData",
          },
        },
        // ✅ preserveNullAndEmptyArrays prevents orders with missing/deleted User docs from being dropped!
        {
          $unwind: {
            path: "$userData",
            preserveNullAndEmptyArrays: true,
          },
        },
        // ✅ Flag: Is this user referred?
        {
          $addFields: {
            isReferred: {
              $cond: {
                if: { $ifNull: ["$userData.referredBy", false] },
                then: true,
                else: false,
              },
            },
          },
        },
        // ✅ Group by User ID and Referral Status to aggregate spends
        {
          $group: {
            _id: {
              userId: "$userId",
              isReferred: "$isReferred",
            },
            orderCount: { $sum: 1 },
            totalSpend: { $sum: "$totalPrice" },
          },
        },
        // ✅ Separate referred vs organic users
        {
          $facet: {
            referred: [
              { $match: { "_id.isReferred": true } },
              {
                $project: {
                  userId: "$_id.userId",
                  orderCount: 1,
                  totalSpend: 1,
                },
              },
            ],
            organic: [
              { $match: { "_id.isReferred": false } },
              {
                $project: {
                  userId: "$_id.userId",
                  orderCount: 1,
                  totalSpend: 1,
                },
              },
            ],
          },
        },
      ]);

      const result = userOrderAggregation[0] || { referred: [], organic: [] };

      // 2. Calculate metrics for both cohorts
      const referredMetrics = calculateCohortMetrics(result.referred);
      const organicMetrics = calculateCohortMetrics(result.organic);

      // 3. Calculate Premiums (Comparison)
      const revenuePremium =
        organicMetrics.lifetimeValue > 0
          ? ((referredMetrics.lifetimeValue - organicMetrics.lifetimeValue) /
              organicMetrics.lifetimeValue) *
            100
          : 0;

      const repeatPremium =
        referredMetrics.repeatPurchaseRate - organicMetrics.repeatPurchaseRate;

      const aovPremium =
        organicMetrics.averageOrderValue > 0
          ? ((referredMetrics.averageOrderValue - organicMetrics.averageOrderValue) /
              organicMetrics.averageOrderValue) *
            100
          : 0;

      // Revenue impact reflects total revenue generated BY the referral program
      const revenueImpact = referredMetrics.totalRevenue;

      // 4. Build Response
      const response: LoyaltyExecutiveSummaryResponse = {
        referred: referredMetrics,
        organic: organicMetrics,
        comparison: {
          revenuePremium: Number(revenuePremium.toFixed(1)),
          repeatPremium: Number(repeatPremium.toFixed(1)),
          aovPremium: Number(aovPremium.toFixed(1)),
          revenueImpact: Number(revenueImpact.toFixed(0)),
        },
        generatedAt: new Date().toISOString(),
      };

      // 5. Cache for 5 Minutes (using safeStringify)
      await redis.set(cacheKey, safeStringify(response), { ex: 300 });
      console.log("✅ Loyalty Executive Summary Cached.");

      return { success: true, data: response };
    } finally {
      await releaseLock(lockKey, requestId);
    }
  } catch (error: any) {
    console.error("Loyalty Executive Engine Error:", error.message);
    return {
      success: false,
      error: error.message || "Failed to fetch executive summary.",
    };
  }
}