// src/app/robots.ts
// ================================================================
// 🤖 ENTERPRISE ROBOTS.TXT ENGINE
// ================================================================
// This file controls search engine crawlers (Google, Bing, etc.) access.
// It explicitly blocks administrative, private, and transactional routes
// while directing crawlers to all available sitemaps (Products, Images, Video, News).
// 
// 🛡️ FEATURES:
// ✅ Strict disallow list for admin, auth, and private user areas
// ✅ References to ALL sitemaps (main, images, video, news)
// ✅ Environment-aware (uses NEXT_PUBLIC_BASE_URL)
// ✅ Supports Next.js 16+ MetadataRoute.Robots type
// ✅ Prevents indexing of staging environments if needed (optional env check)
// ================================================================

import { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL;

  // 🛡️ Safety Check: Deployment ke waqt baseUrl ka hona zaroori hai
  if (!baseUrl) {
    console.warn("⚠️ Missing NEXT_PUBLIC_BASE_URL in robots.ts. Using relative paths.");
    // Fallback to empty string to prevent build failure, but ideally this shouldn't happen.
    // We return an empty array or placeholder to avoid breaking the build.
    return {
      rules: [
        {
          userAgent: "*",
          disallow: "/",
        },
      ],
    };
  }

  // 🚀 All sitemap locations for maximum crawler discoverability
  // Google supports multiple sitemap entries in robots.txt
  const sitemapUrls = [
    `${baseUrl}/sitemap.xml`,                     // Main index (auto-generated by Next.js)
    `${baseUrl}/sitemap-images.xml?page=1`,       // Image sitemap (paginated)
    `${baseUrl}/sitemap-video.xml`,               // Video sitemap
    `${baseUrl}/sitemap-news.xml`,                // News sitemap (last 2 days only)
  ];

  return {
    rules: [
      {
        userAgent: "*", // Sab crawlers ke liye aik hi rule
        allow: "/", // Baqi mukammal website allowed hai

        // 🚫 DISALLOW LIST (Private, Admin & Transactional Routes)
        disallow: [
          // 1. Admin Panels & CMS
          "/admin/", // Payload CMS Admin
          "/studio/", // Sanity Studio (agar future mein use hua toh)

          // 2. User Accounts & Privacy (No-index personal data)
          "/account/", // Customer Dashboard
          "/api/", // Backend API Routes (all of them)
          "/login",
          "/register",
          "/forgot-password",
          "/reset-password/",
          "/verify-email",
          "/verify-phone",
          "/access-denied",

          // 3. E-commerce Transactional Pages (No SEO value, conversion focused)
          "/cart",
          "/checkout/",
          "/wishlist",
          "/order-failure",
          "/order-success/",

          // 4. Temporary, Utility or Low-Value Pages
          "/gift-cards",
          "/sell",
        ],
      },
      // Optional: Googlebot-specific rules (if needed, we can add here)
      // {
      //   userAgent: "Googlebot",
      //   allow: "/",
      //   disallow: ["/api/", "/admin/"],
      // },
    ],
    // 🗺️ Sitemaps: Crawlers ko batana ke sitemap kahan kahan hain
    sitemap: sitemapUrls,
  };
}