// src/lib/reports/operational/components/OperationalReportFooter.tsx

import React from "react";
import { Text, View, StyleSheet } from "@react-pdf/renderer";

interface FooterProps {
  styles: ReturnType<typeof StyleSheet.create>;
}

export const OperationalReportFooter = ({ styles }: FooterProps) => {
  return (
    <View style={styles.footer}>
      <Text>This report is automatically generated by PocketValue Operations Engine.</Text>
      <Text style={styles.verificationNote}>
        * Data is based on revenue-valid orders (Delivered, Completed, Shipped, In Transit, Payment Verified, Processing, Ready to Ship).
      </Text>
      <Text style={styles.verificationNote}>
        ** Limbo statuses include: Pending, Payment Verified, Processing, Ready to Ship, RTO, Return Requested, Return Approved, Refund Initiated, On Hold, Fraud Hold.
      </Text>
    </View>
  );
};